services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: demoservice-api
    environment:
      DB_HOST: mysql #Representa o service que foi criado logo abaixo para o MySQL. Se o nome fosse "batata-frita" isso é o que estaria ai.
    depends_on: #Diz que esse servico depende de outro, entao a ordem de build e start comeca pelo que ele depende.
      - mysql
    ports:
      - 8080:8080
    networks:
      - demoservice-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: focusdatabase
      MYSQL_USER: focususer
      MYSQL_PASSWORD: root123
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - demoservice-network

networks:
  demoservice-network:
    driver: bridge

volumes:
  mysql_data: