logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}/focusdatabase
    username: focususer
    password: root123 #${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: update
    show-sql: true
  application:
    name: demo-service
  output:
    ansi:
      enabled: always

api:
  security:
    token:
      secret: ${JWT_SECRET:my_secret}