spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/focusdatabase
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: update
    show-sql: true
  application:
    name: demo-service